### ISSUE TITLE
RGLConstants.js from wrong location

### ISSUE THREAD

**Issue by raboof** [bsansouci/fruit-ninja#4]
After running `npm run build:web`, starting a local python webserver and visiting http://localhost:8000, http://localhost:8000/node_modules/Reasongl/lib/js/src/RGLConstants.js is fetched, but this file is at http://localhost:8000/node_modules/reprocessing/node_modules/Reasongl/lib/js/src/RGLConstants.js.

(after adding a symlink it otherwise works fine)

**Comment by bsansouci** [comment]
I'm surprised. Does this happen every time? Can you grep inside `node_modules` to find what on earth would require that file from that path? I just tried on a brand new OSX laptop and didn't get this issue. Do you think it's a casing issue once again?

Try changing the name `Reprocessing` inside `bs-dependencies` in the bsconfig

**Comment by raboof** [comment]
I didn't find out what caused this (but I'm not too familiar with npm/require). Cleared `node_modules` and tried again, now it was fine. Perhaps it was a leftover from before I applied #1 I guess?
